export {default as MarsLogo} from './logo/marslogo-removebg-preview.png'
export {default as MarsLogoWhite} from './logo/Screenshot_2026-01-03_at_21.20.01-removebg-preview.png'
export {default as Astronout} from './images/astronout1-removebg-preview.png'
export {default as Teacher1} from './images/teacher1.png'
export {default as Teacher2} from './images/teacher2.png'
export {default as Teacher3} from './images/teacher3.png'
export {default as Beruniy} from './images/beruniy.webp'
export {default as Yunusobod} from './images/yunusobod.webp'
export {default as Chilonzor} from './images/chilonzor.webp'
export {default as Sergeli} from './images/sergeli.webp'
export {default as Mirobod} from './images/mirabod.webp'
export {default as Yunusobod2} from './images/yunusobod2.webp'
export {default as Atxam} from './images/Atxam.png'
export {default as Ruslan} from './images/Ruslan.png'
export {default as Jahongir} from './images/Jahongir.png'
export {default as Child} from './images/child .jpg'
export {default as Child2} from './images/child2.jpg'
export {default as Astranout} from './images/astronaut_jump_2_1.png.webp'